# Generated by Django 6.0.5 on 2026-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
